version: '3.7'
services:
  db:
    image: postgres:13-alpine
    restart: 'no'
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'taskmanagement'
    volumes:
      - .db_data:/var/lib/postgresql/data
